### ISSUE TITLE
Account for whitespace

### ISSUE THREAD

**Issue by derdesign** [chjj/liquor#2]
Hi there,

Great work! I've just implemented your engine in [CoreJS](https://github.com/derdesign/CoreJS). 

Maybe I'm missing something, but I think the rendered output doesn't account for whitespace in the generated code. For example, consider the following code:

``` javascript
  var liquor = require('liquor'),
      template = '<h1>#{title}</h1>\n\n<p>Hello #{name}</p>\n\n\n\n<p>Howdy</p>';

  // template = template.replace(/\n/gm, '\\n\n');

  var tpl = liquor.compile(template),
      buf = tpl({name: 'Ernie', title: 'My Application'});

  console.log(buf);
  process.exit();
```

This renders the following:

```
<h1>My Application</h1><p>Hello Ernie</p><p>Howdy</p>
```

If you uncomment the line in the code above, it fixes the white space and it renders as written.

Maybe adding a `pretty` option would be good. Maybe it's there, sorry if I missed anything!

Regards,
Ernie.-

**Comment by chjj** [comment]
Yeah, I see the problem. I must have added that line feed escape without buffering the line feeds in the first place. I tend to like the more minified look, but I guess it isn't truly minified. I can put the line feeds in.

Anyway, glad to hear you put it to use. I'll push a fix in a minute.

**Comment by chjj** [comment]
Pushed to npm. The newline preservation is behind a `pretty` option.

30a27d7e0b7f0bad4b98b3418defc9f4f41e730c

**Comment by derdesign** [comment]
Sweet, thanks :)

**Comment by chjj** [comment]
By the way, you should remove this line from your framework:

``` js
data = data.replace(/\n/, '\\n\n');
```

The only reason that worked in the first place was because of this line: https://github.com/chjj/liquor/commit/30a27d7e0b7f0bad4b98b3418defc9f4f41e730c#L3R77

It shouldn't have been there in the first place. I removed it.

**Comment by derdesign** [comment]
Ah right!, I forgot to remove the line... Thanks for letting me know.

**Comment by derdesign** [comment]
Howdy Chris, After using your engine for a while, I've now noticed that the pretty option doesn't preserve indentation. Is there an option where I can switch tabs on ? Any help is appreciated.

**Comment by chjj** [comment]
v0.0.3 just pushed to npm. It should preserve indentation and also remove the levels of indentation added with if/not/iteration statements.

**Comment by derdesign** [comment]
Once again, Thanks! :)

**Comment by derdesign** [comment]
Ah, btw it seems like vertical spacing is lost after the first block of text. Check out [this paste](http://paste.pocoo.org/show/562317/).

**Comment by chjj** [comment]
Yeah, I have it eat extra line feeds. I don't know how desirable or undesirable most people will find it. I think it's an easy way to keep things "pretty" given that most html doesn't include significant whitespace.

**Comment by derdesign** [comment]
Yes, it's a good optimization and I totally agree with you. It does the job of keeping the code pretty & clean removing undesirable extra line feeds & spaces. I think the only thing missing is to  add just one line feed after each block, maybe replace  `/\n+/g` with `/\n\n/` would help maintain code readability, just to keep the blocks separated. What do you think ?

**Comment by chjj** [comment]
The problem is, liquor has no concept of "blocks". It doesn't pay attention to html. If it's cleaning up line feeds where they shouldn't be, it might end up adding 2 where they shouldn't be with that approach. 

I could always remove the line-feed-eating feature though.

**Comment by derdesign** [comment]
Yeah, I think it's better, since if one wants to render the code unprettified, we just set `pretty` to off, and it will render it already compressed without any spaces.

**Comment by derdesign** [comment]
Aha, nevermind,  just discovered the `indent` option!

**Comment by chjj** [comment]
Ah, yeah. I added that because I think it might be useful in a case like this:

``` html
<!doctype html>
<title>Hello!</title>
<section>
`partial('body', { indent: 2 })`
</section>
```

If you want to keep really strict indentation.
